### ISSUE TITLE
`perseus export --serve` does not work in 0.4.0-beta.12

### ISSUE THREAD

**Issue by marienz** [framesurge/perseus#249]
This issue is reporting a bug in the code of Perseus. Details of the scope will be available in issue labels.
The author described their issue as follows:
> `perseus export --serve` does not work in 0.4.0-beta.12: I get a build error that I suspect is triggered by building Perseus with neither `--cfg=engine` nor `--cfg=client` (because that would result in no definition of `web_log`, which is the first error):

```
  [1/3] 📦 Exporting your app's pages...✅
  [2/3] 🏗️  Building your app to Wasm...✅
...
   Compiling perseus v0.4.0-beta.12
error[E0432]: unresolved import `crate::web_log`
   --> /home/marienz/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.4.0-beta.12/src/lib.rs:157:13
    |
157 |     pub use crate::web_log;
    |             ^^^^^^^^^^^^^^ no `web_log` in the root

error[E0432]: unresolved imports `crate::PerseusNodeType`, `crate::Request`
   --> /home/marienz/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.4.0-beta.12/src/lib.rs:160:21
    |
160 |     pub use crate::{PerseusNodeType, Request};
    |                     ^^^^^^^^^^^^^^^  ^^^^^^^ no `Request` in the root
    |                     |
    |                     no `PerseusNodeType` in the root

error[E0432]: unresolved import `crate::PerseusNodeType`
 --> /home/marienz/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.4.0-beta.12/src/translator/lightweight.rs:3:5
  |
3 | use crate::PerseusNodeType;
  |     ^^^^^^^^^^^^^^^^^^^^^^ no `PerseusNodeType` in the root

error[E0432]: unresolved import `crate::utils::PerseusDuration`
 --> /home/marienz/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.4.0-beta.12/src/template/core/setters.rs:2:5
  |
2 | use crate::utils::PerseusDuration;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PerseusDuration` in `utils`

error[E0432]: unresolved imports `decode_time_str::ComputedDuration`, `decode_time_str::PerseusDuration`
  --> /home/marienz/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.4.0-beta.12/src/utils/mod.rs:25:27
   |
25 | pub use decode_time_str::{ComputedDuration, InvalidDuration, PerseusDuration}; /* These have dummy equivalents for the browser */
   |                           ^^^^^^^^^^^^^^^^                   ^^^^^^^^^^^^^^^ no `PerseusDuration` in `utils::decode_time_str`
   |                           |
   |                           no `ComputedDuration` in `utils::decode_time_str`

error[E0392]: parameter `M` is never used
   --> /home/marienz/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.4.0-beta.12/src/init.rs:111:36
    |
111 | pub struct PerseusAppBase<G: Html, M: MutableStore, T: TranslationsManager> {
    |                                    ^ unused parameter
    |
    = help: consider removing `M`, referring to it in a field, or using a marker such as `PhantomData`

error[E0392]: parameter `T` is never used
   --> /home/marienz/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.4.0-beta.12/src/init.rs:111:53
    |
111 | pub struct PerseusAppBase<G: Html, M: MutableStore, T: TranslationsManager> {
    |                                                     ^ unused parameter
    |
    = help: consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`

error[E0392]: parameter `G` is never used
  --> /home/marienz/.cargo/registry/src/github.com-1ecc6299db9ec823/perseus-0.4.0-beta.12/src/reactor/mod.rs:71:20
   |
71 | pub struct Reactor<G: Html> {
   |                    ^ unused parameter
   |
   = help: consider removing `G`, referring to it in a field, or using a marker such as `PhantomData`

Some errors have detailed explanations: E0392, E0432.
For more information about an error, try `rustc --explain E0392`.
error: could not compile `perseus` due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
```

The steps to reproduce this issue are as follows:
> - Install Perseus CLI 0.4.0-beta.12
> - Run `perseus export -s` in a project using `perseus::main_export` (the Perseus website at version 0.4.0-beta12 and a small example fail the same way).

A minimum reproducible example is available at <>.
- Hydration-related: false
- The author is willing to attempt a fix: true 

<details>
<summary>Tribble internal data</summary>

dHJpYmJsZS1yZXBvcnRlZCxDLWJ1ZyxBLWNsaSxhdXRob3Itd2lsbGluZy10by1pbXBs

</details>

**Comment by arctic-hen7** [comment]
Yes, I'm aware of this happening only sometimes, and I've yanked beta 12 accordingly. To my understanding for now, this would appear to be a duplicate of #246, because I've only observed this error when using `cargo-clif`. Are you seeing this with the default compiler? (Note that this may well be a bug that only occurs sometimes.)

**Comment by arctic-hen7** [comment]
Note that I was able to get the website working perfectly after `cargo clean` without using the experimental compiler backend.

**Comment by arctic-hen7** [comment]
Actually, now I think about it, this could just be a `cargo clean` problem coming from the old beta versions. If you're able to reproduce this *after* a `cargo clean && perseus clean` (remember Perseus maintains its own `target/` directories in `dist/`), it's definitely a bug.

**Comment by arctic-hen7** [comment]
Now getting this in CI for the website on the new beta 13 (which fixed some fatal bugs from beta 12)...but not locally...

**Comment by arctic-hen7** [comment]
Working theory: lockfile generation is not passed the `RUSTFLAGS`, meaning it will only work if there's a `.cargo/config.toml` in your project setting the necessary flags.

**Comment by arctic-hen7** [comment]
@marienz I think this issue is fixed now in v0.4.0-beta.14, would you mind giving that a try? If you're still having issues, do try a `cargo clean && perseus clean`. I'll close this for now.

**Comment by marienz** [comment]
I am not using `cargo-clif` (I only found out about it just now, from this bug and #246).

I can no longer reproduce the problem after upgrading perseus-cli to 0.4.0-beta.14. Thanks for the fix!
